name: Deploy project

on:
  push:
    branches: [master]

jobs:
  Build-Project:
    environment: production

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: node -v
      - run: pnpm -v

      - name: Build project
        run: |
          if ! pnpm i --frozen-lockfile; then
              echo "Install dependencies failed"
              exit 1
          fi

          export API_URL=/
          if ! pnpm run build; then
              echo "Build static failed"
              exit 1
          fi

          tar -czf dist.tar.gz dist

      - name: Upload to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          scp -o StrictHostKeyChecking=no -i ./private_key.pem dist.tar.gz  $SERVER_USER@$SERVER_IP:/home/$SERVER_USER
          ssh -i ./private_key.pem $SERVER_USER@$SERVER_IP '
            cd /home/'$SERVER_USER'
            tar -xzf dist.tar.gz
            mv dist /var/www/loadept
            sudo systemctl restart nginx
          '
